# Generated by Django 4.1.6 on 2023-03-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0009_alter_rideinfo_destinationname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideinfo',
            name='rideType',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='rideinfo',
            name='status',
            field=models.CharField(max_length=2),
        ),
    ]
