# Generated by Django 4.1.6 on 2023-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0011_alter_rideinfo_ridetype_alter_rideinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideinfo',
            name='rideType',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='rideinfo',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('cancelled', 'cancelled'), ('ongoing', 'ongoing')], default='ongoing', max_length=10),
        ),
    ]
