# Generated by Django 4.1.6 on 2023-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0012_alter_rideinfo_ridetype_alter_rideinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideinfo',
            name='rideType',
            field=models.CharField(choices=[('book', 'book'), ('offer', 'offer')], max_length=5),
        ),
    ]
