# Generated by Django 4.1.6 on 2023-03-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0013_alter_rideinfo_ridetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vehicleInformation',
            new_name='vehicleInfo',
        ),
    ]
