# Generated by Django 4.1.6 on 2023-03-17 10:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0015_remove_riderinfo_citizenship_photo_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderinfo',
            name='citizenship_image_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='citizenship_image_back'),
        ),
        migrations.AlterField(
            model_name='riderinfo',
            name='citizenship_image_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='citizenshipPictures'),
        ),
        migrations.AlterField(
            model_name='riderinfo',
            name='id_confirmation_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='idConfirmationPictures'),
        ),
    ]
