# Generated by Django 4.2 on 2023-04-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RideSharing", "0016_alter_riderinfo_citizenship_image_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rideinfo",
            name="date",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="rideinfo",
            name="time",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
