# Generated by Django 4.2 on 2023-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0018_alter_userinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideinfo',
            name='rideType',
            field=models.CharField(choices=[('book', 'book'), ('offer', 'offer')], default='offer', max_length=5),
        ),
    ]
