# Generated by Django 4.2 on 2023-04-27 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0019_alter_rideinfo_ridetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideinfo',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RideSharing.riderinfo'),
        ),
        migrations.AlterField(
            model_name='rideinfo',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RideSharing.userinfo'),
        ),
    ]
