# Generated by Django 4.2 on 2023-04-28 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0020_rideinfo_rider_alter_rideinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideSharing.rideinfo'),
        ),
    ]
