# Generated by Django 4.2 on 2023-04-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0021_alter_vehicleinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinfo',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RideSharing.riderinfo'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideSharing.userinfo'),
        ),
    ]
